### ISSUE TITLE
Error: Cannot read property 'properties' of undefined

### ISSUE THREAD

**Issue by g0d1ike** [splunk/splunk-tableau-wdc#11]
I Followed your Instruction, used docker to deploy the wdc，but when I connect to /src/splunkConnector.html and submit the information to Test Connection, but the Wdc return msg "Failed! Verify entered server details." , and I have view the Chrome Console,  some error have happend. The error msg at console is follow:
"
POST http://my_ip/proxy/services/auth/login?output_mode=json 500 (Internal Server Error)
send @ jquery.min.js:2
ajax @ jquery.min.js:2
makeRequest @ splunk.min.js:5
request @ splunk.min.js:5
(anonymous) @ splunk.min.js:5
post @ splunk.min.js:5
(anonymous) @ splunk.min.js:5
login @ splunk.min.js:5
(anonymous) @ splunk.min.js:5
_requestWrapper @ splunk.min.js:5
(anonymous) @ splunk.min.js:5
get @ splunk.min.js:5
(anonymous) @ splunk.min.js:5
get @ splunk.min.js:5
(anonymous) @ splunk.min.js:5
fetch @ splunk.min.js:5
(anonymous) @ splunk.min.js:5
(anonymous) @ splunk.min.js:5
serverInfo @ splunk.min.js:5
(anonymous) @ splunkConnector.js:67
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
common.js:7 TypeError: Cannot read property 'properties' of undefined
    at splunkConnector.js:69
    at splunk.min.js:5
    at splunk.min.js:5
    at e (splunk.min.js:5)
    at e (splunk.min.js:5)
    at Object.error (splunk.min.js:5)
    at u (jquery.min.js:2)
    at Object.fireWith [as rejectWith] (jquery.min.js:2)
    at k (jquery.min.js:2)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2)
common.js:7 err
common.js:7 Error timeout
"
My splunk version is 7.2.4, and OS version is Centos7.5 bit 64
According the error from chrome console, I think maybe some error on splunkConnector.js .
Please help me for it when you at  free time.

**Comment by mayurah** [comment]
@g0d1ike were you able to fix (or reproduce) this?

**Comment by mayurah** [comment]
Inactive - assuming this network issue (proxy mode) has been resolved.
