### ISSUE TITLE
Splunk Data sent to Tableau using WDC was only sending data through String (Date and Numeric values are also sent as strings)

### ISSUE THREAD

**Issue by pmslssr** [splunk/splunk-tableau-wdc#13]
While sending data I want to send the data which is in the numeric or date form to be in the same format in tableau. Currently, It is sent as a string when checking in tableau. Please let me know if anything can be done to send in the same format (Number as number and string as string)

**Comment by mayurah** [comment]
@pmslssr  This can be done by evaluating data type and changing them in JS.  

I will let someone in community pick that as "good first issue".

**Comment by pmslssr** [comment]
Can you tell which JS should be changed in order to make sure that datatype is handled properly and sent as the same to Tableau end?

**Comment by mayurah** [comment]
@pmslssr 

- [ ] Here is the specific line which assigns dataType: https://github.com/splunk/splunk-tableau-wdc/blob/master/src/splunk-wdc.js#L170
- [ ] Might help as a start on how you can detect data type in JavaScript: https://stackoverflow.com/a/175787/866571
- [ ] Detect datatype before assigning
- [ ] Assign detected datatype

**Comment by pmslssr** [comment]
@mayurah 
JS was updated two days back. 
Now, Can you refer to the exact line where it is assigning data type?.
It will help us a lot

**Comment by mayurah** [comment]
@pmslssr  Updated comment with new line and code sample.

**Comment by pmslssr** [comment]
@jrzmurray Shall I pull WDC again so that it will solve this issue when I refresh from tableau end ?

**Comment by jrzmurray** [comment]
@pmslssr you can pull my forked version now (source of the PR), or wait for this PR to be merged.
