### ISSUE TITLE
Tableau Server 2018.1 issue on extraction Splunk WDC

### ISSUE THREAD

**Issue by duuhsousa** [splunk/splunk-tableau-wdc#14]
After I've ipdated my whitelist on Tableau Server 2018.1 to get extracts from Splunk WDC, I am facing the error below.

`2019-07-26 10:02:37.587 -0300 (Default,,,,628517,:refresh_extracts,-) scheduled-background-job-runner-1 backgrounder: ERROR com.tableausoftware.backgrounder.runner.BackgroundJobRunner - Error executing background job: RefreshExtracts
java.util.concurrent.ExecutionException: com.tableausoftware.nativeapi.dll.DataSourceException: SyntaxError: JSON Parse error: Unexpected identifier "undefined"   file: http://splunkserver/static/splunk.min.js   line: 5`

Can you help me? The Tableau Desktop works fine, this issue shows up when I configure extraction on Tableau Server.

**Comment by mayurah** [comment]
@duuhsousa This looks like more of an internal networking issue as Tableau Server is not able to find host `splunkserver`.
