### ISSUE TITLE
Re Opening Splunk Data sent to Tableau using WDC was only sending data through String (Date Values are also sent as strings)

### ISSUE THREAD

**Issue by praneeth2968** [splunk/splunk-tableau-wdc#21]
Recent fix fixed the number and string type. But Date in splunk is coming as Number and String only even if the field was date.

Below SPL Query is the proof
| makeresults
| eval stringTime=strftime(_time,"%c")
| eval TypeEpochTime=typeof(_time), TypeStringTime=typeof(stringTime)

![Datatype Issue]
(https://user-images.githubusercontent.com/25930565/67003950-cb046b00-f0fc-11e9-8d5e-de34676bee68.PNG)

**Comment by mayurah** [comment]
You can use Tableau's built-in function to convert string to data-type you intend to have for analytics.
